Learning_templates/Learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views
urlpatterns = [
    path('',views.index,name="index"),
    path('basicapp/',include("basicapp.urls")),
    path('admin/', admin.site.urls),
]

Learning_templates/basicapp/urls.py
from django.urls import path
from basicapp import views
app_name="basicapp"

urlpatterns=[
    path('relative/',views.relative_urls_templates,name="relative_urls_templates"),
    path('other/',views.other,name="other"),
 ]

Learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

Learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"basicapp/index.html")
def other(request):
    return render(request,"basicapp/other.html")
def relative_urls_templates(request):
    return render(request,"basicapp/relative_urls_templates.html")

Learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="#">DJANGO</a></li>
          <li><a class="navbar-link" href="#">Admin</a></li>
          <li><a class="navbar-link" href="#">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">



    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>


  </body>
</html>

Learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
 {% block body_block %}

 <h1>Welcome to index</h1>
 <h2>This is index html page showing</h2>
{% endblock %}

Learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
 {% block body_block %}

 <h1>Welcome to other</h1>
 <h2>This is other html page showing</h2>
{% endblock %}

Learning_templates/templates/basicapp/relative_urls_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative</h1>
    <a href="{%url 'basicapp:other'%}">the other</a>
    <a href="{%url 'index'%}">The index</a>
  </body>
</html>